# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20170909_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='created_at',
        ),
    ]
